version: "3"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80/tcp"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./static:/staticfiles
    depends_on:
      - django_web

  django_web:
    image: cuh123/docker_autotest:latest
    container_name: django_web

    command: gunicorn --bind 0.0.0.0:8000 config.wsgi:application
    volumes:
      - ./static:/usr/src/app/staticfiles
    expose:
      - "8000"

